[project]
name = "jacks-car-rental"
version = "0.1.0"
description = "Solution to Jack's Car Rental problem."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "numpy>=2.0.2",
    "scipy>=1.15.2",
]
